---
title: "Section 14: Data Manipulation in R"
output: html_notebook
---

Guide to Using Dplyr

```{r}
library(dplyr)
library(nycflights13)

head(flights)
summary(flights)

head(filter(flights,month==11,day==3,carrier=='AA')) # conditional selection - apparently easier than subset call

slice(flights,1:10) #select rows by position

head(arrange(flights,desc(air_time))) #orders data frame

head(select(flights,carrier)) #select specific columns

head(rename(flights,airline_carrier = carrier))#duh

distinct(select(flights,carrier))#distinct values

mutate(flights, new_col = arr_delay-dep_delay) #create new columns with function

transmute()#same as mutate... this only returns new column

summarise(flights,avg_air_time=mean(air_time,na.rm = TRUE)) #run a function on a column

sample_n(flights,10) #returns 10 random rows

sample_frac(flights,0.20) #returns 20% of tows



```

Pipe Operator

```{r}
library(dplyr)

df <- mtcars

result <- arrange(sample_n(filter(df,mpg>20),size=5), desc(mpg))

print(result)


a <- filter(df,mpg>20)
b <- sample_n(a,size=5)


df %>% filter(mpg>20) %>% sample_n(size=5) %>% arrange(desc(mpg)) #pipe operator - chain
```


Dplyr Training exercise

```{r}
library(dplyr)

head(mtcars)

filter(mtcars, mpg>20, cyl==6)

head(arrange(mtcars,cyl,desc(wt)))

head(select(mtcars,mpg,hp))

head(distinct(mtcars,gear))

head(mutate(mtcars, Performance = hp/wt ))

summarise(mtcars,avg_mpg=mean(mpg,na.rm=TRUE))

mtcars %>% filter(cyl==6) %>% summarise(avg_hp = mean(hp))
```


Tidyr

```{r}
#Maybe I'm tired but I am glazing over this lecture... what is the point of this library?

library(tidyr)
library(data.table)

comp <- c(1,1,1,2,2,2,3,3,3)
yr <- c(1998,1999,2000,1998,1999,2000,1998,1999,2000)
q1 <- runif(9, min=0, max=100)
q2 <- runif(9, min=0, max=100)
q3 <- runif(9, min=0, max=100)
q4 <- runif(9, min=0, max=100)

df <- data.frame(comp=comp,year=yr,Qtr1 = q1,Qtr2 = q2,Qtr3 = q3,Qtr4 = q4)

df


gather(df,Quarter,Revenue,Qtr1:Qtr4)

stocks <- data.frame(
  time = as.Date('2009-01-01') + 0:9,
  X = rnorm(10, 0, 1),
  Y = rnorm(10, 0, 2),
  Z = rnorm(10, 0, 4)
)

stocks.gathered <- stocks %>% gather(stock,price,X:Z)
stocks.gathered <- stocks %>% gather(stock,price,X,Y,Z)
head(stocks.gathered)


stocks.gathered %>% spread(stock,price)

spread(stocks.gathered,stock,price)

spread(stocks.gathered,time,price)

df <- data.frame(new.col=c(NA,'a.x','b.y','c.z'))

separate(df,new.col,c('ABC','XYZ'))

df.sep <- separate(data=df,col=new.col,into=c('abc','xyz'),sep='-')

unite(df.sep,new.joined.col,abc,xyz)

```

