---
title: "Section 9: R Data Frames"
output: html_notebook
---
Data Frame Basics
```{r}
#state.x77
#USPersonalExpenditure
#women
# The three comments above are built-in databases
data() #way to see all datasets
head(state.x77) #first 6 rows
tail(state.x77) #last 6 rows
str(state.x77) #structure of dataframe
summary(state.x77) #summary of some central tendencies
days <- c('Mon','Tue','Wed','Thu','Fri')
temp <- c(22.2,21,23,24.3,25)
rain <- c(T,T,F,F,T)
df <- data.frame(days,temp,rain) #make a data frame... vectors are columns values are rows
df
```

Overview of Data Frame Operations - Part 1

```{r}
#Creating Data Frames
empty <- data.frame()
c1 <- 1:10
c1
letters
c2 <- letters[1:10] #a-j
df <- data.frame(col.name.1 = c1, col.name.2 = c2)
df
#d2 <- read.cxv('some_file.csv')
write.csv(df,file = 'saved_df.csv')# writing csv
df2 <- read.csv('saved_df.csv') #reading csv
nrow(df) #number rows
ncol(df) #number columns
colnames(df)
rownames(df)
str(df) #returns structure of data frame
summary(df) #summary of data
df[[5,2]] #row 5, column 2
df[[5,'col.name.2']] #more useful to use column name
df[[2,'col.name.1']] <- 9999 #reassigning value
head(mtcars) #returns 6 rows
mtcars$mpg #vector of mpg values
mtcars[,'mpg'] #vector of mpg values
mtcars[['mpg']]#vector of mpg values
mtcars['mpg'] #data frame of values
head(mtcars[c('mpg','cyl')]) #df with specific values
```

Data Frame Operations Part 2

```{r}
df2 <- data.frame(col.name.1 = 2000, col.name.2 = 'new')
df2
df
df$newcol <- 2*df$col.name.1 #add new column with function
df$newcol.copy <- df$newcol #copyin column
df
df[,'newcol.copy2'] <- df$newcol #also copying column
colnames(df)
colnames(df) <- c('1','2','3','4','5') #renaming all columns with vecotr
head(df)
colnames(df)[1] <- 'NEW COL NAME'
df[1:10,] #select first ten rows
df[1:3,] #select first three rows
head(df,7) #return 7 rows
head(df)
df[-2,] #everything but first two columns
head(mtcars)
mtcars[ mtcars$mpg > 20,] #returning rows where mpg is greater than 20
```

Data Frames Exercises:
```{r}
#Ex1:
Names <- c('Sam','Frank','Amy')
Age <- c(22,25,26)
Weight <- c(150,165,120)
Sex <- c('M','M','F')
df <- data.frame(Names,Age,Weight,Sex)
df
#Use row.names to make the first column invisible.

#Ex2:
is.data.frame(mtcars)

#Ex3:
mat <- matrix(1:25,nrow=5)
mat_df <- as.data.frame(mat)
mat_df

#Ex4:
df <- mtcars

#Ex5:

head(df,6)

#Ex6:

mean(df$mpg)

#Ex7:

df[(df$cyl == 6),]

#Ex8:

df[c('am','gear','carb')]

#Ex9:

df$performance <- (df$hp / df$wt)

#Ex10:

df$performance <- round(df$performance,2)
head(df)

#Ex 10-2

mean((df[(df$hp > 100 & df$wt > 2.5),])$mpg)

#Ex 11

df['Hornet Sportabout','mpg']

```


